// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2025-01-17 13:20:05.284019 +0000 GMT m=+0.000477917
package localiser

import (
	"fmt"
	"strings"

	"github.com/go-playground/locales"
	"github.com/go-playground/locales/en_GB"
	"github.com/go-playground/locales/en_US"
	"github.com/go-playground/locales/fr"
	"github.com/go-playground/locales/es"
)

func Parse(localeStr string) (locales.Translator, error) {
	selectedLocale := en_GB.New()
	var err error

	switch strings.ToLower(localeStr) {
	case "en_gb", "gb", "uk":
		selectedLocale = en_GB.New()
	case "en_us", "en", "us":
		selectedLocale = en_US.New()
	case "fr":
		selectedLocale = fr.New()
	case "es":
		selectedLocale = es.New()
	default:
		err = fmt.Errorf("Unsupported locale: %q", localeStr)
	}

	return selectedLocale, err
}
