// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2025-03-14 18:42:20.861015 +0000 GMT m=+0.000775293
package localiser

import (
	"fmt"
	"strings"

	"github.com/go-playground/locales"
	"github.com/go-playground/locales/en_GB"
	"github.com/go-playground/locales/en_US"
	"github.com/go-playground/locales/fr_FR"
	"github.com/go-playground/locales/es_ES"
)

func Parse(localeStr string) (locales.Translator, error) {
	selectedLocale := en_GB.New()
	var err error

	switch strings.ToLower(localeStr) {
	case "en_gb", "gb", "uk":
		selectedLocale = en_GB.New()
	case "en_us", "en", "us":
		selectedLocale = en_US.New()
	case "fr_fr", "fr":
		selectedLocale = fr_FR.New()
	case "es_es", "es":
		selectedLocale = es_ES.New()
	default:
		err = fmt.Errorf("Unsupported locale: %q", localeStr)
	}

	return selectedLocale, err
}
